/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_calculator;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Mohamed
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfResult = new javax.swing.JTextField();
        jbutton_1 = new javax.swing.JButton();
        jbutton_2 = new javax.swing.JButton();
        jbutton_3 = new javax.swing.JButton();
        jbutton_4 = new javax.swing.JButton();
        jbutton_5 = new javax.swing.JButton();
        jbutton_6 = new javax.swing.JButton();
        jbutton_0 = new javax.swing.JButton();
        jbutton_7 = new javax.swing.JButton();
        jbutton_8 = new javax.swing.JButton();
        jbtSubtract = new javax.swing.JButton();
        jbtDivide = new javax.swing.JButton();
        jbtAdd = new javax.swing.JButton();
        jbtdecimal = new javax.swing.JButton();
        jbtEqual = new javax.swing.JButton();
        jbutton_9 = new javax.swing.JButton();
        jbtcos = new javax.swing.JButton();
        jbtsin = new javax.swing.JButton();
        jbtfac = new javax.swing.JButton();
        jbtTan = new javax.swing.JButton();
        jbtClear = new javax.swing.JButton();
        jbtsqrt = new javax.swing.JButton();
        jbtMultiply = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        jtfResult.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jbutton_1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbutton_1.setText("1");
        jbutton_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton_1ActionPerformed(evt);
            }
        });

        jbutton_2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbutton_2.setText("2");
        jbutton_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton_2ActionPerformed(evt);
            }
        });

        jbutton_3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbutton_3.setText("3");
        jbutton_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton_3ActionPerformed(evt);
            }
        });

        jbutton_4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbutton_4.setText("4");
        jbutton_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton_4ActionPerformed(evt);
            }
        });

        jbutton_5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbutton_5.setText("5");
        jbutton_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton_5ActionPerformed(evt);
            }
        });

        jbutton_6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbutton_6.setText("6");
        jbutton_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton_6ActionPerformed(evt);
            }
        });

        jbutton_0.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbutton_0.setText("0");
        jbutton_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton_0ActionPerformed(evt);
            }
        });

        jbutton_7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbutton_7.setText("7");
        jbutton_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton_7ActionPerformed(evt);
            }
        });

        jbutton_8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbutton_8.setText("8");
        jbutton_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton_8ActionPerformed(evt);
            }
        });

        jbtSubtract.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbtSubtract.setText("-");
        jbtSubtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSubtractActionPerformed(evt);
            }
        });

        jbtDivide.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtDivide.setText("/");
        jbtDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDivideActionPerformed(evt);
            }
        });

        jbtAdd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtAdd.setText("+");
        jbtAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAddActionPerformed(evt);
            }
        });

        jbtdecimal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtdecimal.setText(".");
        jbtdecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtdecimalActionPerformed(evt);
            }
        });

        jbtEqual.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtEqual.setText("=");
        jbtEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEqualActionPerformed(evt);
            }
        });

        jbutton_9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbutton_9.setText("9");
        jbutton_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton_9ActionPerformed(evt);
            }
        });

        jbtcos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtcos.setText("cos");
        jbtcos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtcosActionPerformed(evt);
            }
        });

        jbtsin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtsin.setText("sin");
        jbtsin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtsinActionPerformed(evt);
            }
        });

        jbtfac.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtfac.setText("fac");
        jbtfac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtfacActionPerformed(evt);
            }
        });

        jbtTan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtTan.setText("tan");
        jbtTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtTanActionPerformed(evt);
            }
        });

        jbtClear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtClear.setText("clear");
        jbtClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtClearActionPerformed(evt);
            }
        });

        jbtsqrt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtsqrt.setText("sqrt");
        jbtsqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtsqrtActionPerformed(evt);
            }
        });

        jbtMultiply.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtMultiply.setText("*");
        jbtMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtMultiplyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtfResult)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbutton_3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbutton_4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbutton_5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbutton_0, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbutton_1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbutton_2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbutton_6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbutton_7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbutton_9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbtdecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbutton_8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jbtAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jbtSubtract, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jbtMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jbtsin, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtcos, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jbtTan, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtfac, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41))))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jbtClear, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtsqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtfResult, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jbutton_0, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                .addComponent(jbutton_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtSubtract, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbutton_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbutton_3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbutton_4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbutton_5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtcos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtsin, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbutton_8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbutton_7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbutton_6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtdecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbutton_9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtfac, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtTan, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtsqrt, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jbtClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtdecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtdecimalActionPerformed
        jtfResult.setText(jtfResult.getText() + ".");
    }//GEN-LAST:event_jbtdecimalActionPerformed

    private void jbtAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAddActionPerformed
        jtfResult.setText(jtfResult.getText() + "+");
    }//GEN-LAST:event_jbtAddActionPerformed

    private void jbtSubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSubtractActionPerformed
        jtfResult.setText(jtfResult.getText() + "-");
    }//GEN-LAST:event_jbtSubtractActionPerformed

    private void jbtMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtMultiplyActionPerformed
        jtfResult.setText(jtfResult.getText() + "*");
    }//GEN-LAST:event_jbtMultiplyActionPerformed

    private void jbtDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDivideActionPerformed
        jtfResult.setText(jtfResult.getText() + "/");
    }//GEN-LAST:event_jbtDivideActionPerformed

    private void jbtsinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtsinActionPerformed
        if (jtfResult.getText().contains("*") || jtfResult.getText().contains("/")
                || jtfResult.getText().contains("+") || jtfResult.getText().contains("-")) {
            jtfResult.setText("sin(" + jtfResult.getText() + ")"
                    + "=" + Double.toString(Math.sin(Math.toRadians(calc(jtfResult.getText())))));
        } else {
            jtfResult.setText("sin(" + jtfResult.getText() + ")"
                    + "=" + Double.toString(Math.sin(Math.toRadians(Double.parseDouble(jtfResult.getText())))));
        }
    }//GEN-LAST:event_jbtsinActionPerformed

    private void jbtcosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtcosActionPerformed
        if (jtfResult.getText().contains("*") || jtfResult.getText().contains("/")
                || jtfResult.getText().contains("+") || jtfResult.getText().contains("-")) {
            jtfResult.setText("cos(" + jtfResult.getText() + ")"
                    + "=" + Double.toString(Math.cos(Math.toRadians(calc(jtfResult.getText())))));
        } else {
            jtfResult.setText("cos(" + jtfResult.getText() + ")"
                    + "=" + Double.toString(Math.cos(Math.toRadians(Double.parseDouble(jtfResult.getText())))));
        }
    }//GEN-LAST:event_jbtcosActionPerformed

    private void jbtTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtTanActionPerformed
        if (jtfResult.getText().contains("*") || jtfResult.getText().contains("/")
                || jtfResult.getText().contains("+") || jtfResult.getText().contains("-")) {
            jtfResult.setText("tan(" + jtfResult.getText() + ")"
                    + "=" + Double.toString(Math.tan(Math.toRadians(calc(jtfResult.getText())))));
        } else {
            jtfResult.setText("tan(" + jtfResult.getText() + ")"
                    + "=" + Double.toString(Math.tan(Math.toRadians(Double.parseDouble(jtfResult.getText())))));
        }
    }//GEN-LAST:event_jbtTanActionPerformed

    private void jbtsqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtsqrtActionPerformed
        if (jtfResult.getText().contains("*") || jtfResult.getText().contains("/")
                || jtfResult.getText().contains("+") || jtfResult.getText().contains("-")) {
            jtfResult.setText("sqrt(" + jtfResult.getText() + ")" + "="
                    + Double.toString(Math.sqrt(calc(jtfResult.getText()))));
        } else {
            jtfResult.setText("sqrt(" + jtfResult.getText() + ")" + "="
                    + Double.toString(Math.sqrt(Double.parseDouble(jtfResult.getText()))));
        }
    }//GEN-LAST:event_jbtsqrtActionPerformed

    private void jbtfacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtfacActionPerformed
        jtfResult.setText("fac(" + jtfResult.getText() + ")" + "="
                + Double.toString(fac(jtfResult.getText())));
    }//GEN-LAST:event_jbtfacActionPerformed

    private void jbtEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEqualActionPerformed
        if ((jtfResult.getText().startsWith("+")) || (jtfResult.getText().startsWith("-"))
                || (jtfResult.getText().startsWith("*")) || (jtfResult.getText().startsWith("/"))
                || (jtfResult.getText().endsWith("+")) || (jtfResult.getText().endsWith("-"))
                || (jtfResult.getText().endsWith("*")) || (jtfResult.getText().endsWith("/"))) {
            JOptionPane.showMessageDialog(null, "found error in input");
        } else {
            jtfResult.setText(jtfResult.getText() + "="
                    + Double.toString(calc(jtfResult.getText())));
        }
    }//GEN-LAST:event_jbtEqualActionPerformed

    private void jbtClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtClearActionPerformed
        jtfResult.setText("");
        jbtEqual.setEnabled(true);
    }//GEN-LAST:event_jbtClearActionPerformed

    private void jbutton_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton_0ActionPerformed
        jtfResult.setText(jtfResult.getText() + "0");
    }//GEN-LAST:event_jbutton_0ActionPerformed

    private void jbutton_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton_1ActionPerformed
       jtfResult.setText(jtfResult.getText() + "1");
    }//GEN-LAST:event_jbutton_1ActionPerformed

    private void jbutton_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton_2ActionPerformed
        jtfResult.setText(jtfResult.getText() + "2");
    }//GEN-LAST:event_jbutton_2ActionPerformed

    private void jbutton_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton_3ActionPerformed
       jtfResult.setText(jtfResult.getText() + "3");
    }//GEN-LAST:event_jbutton_3ActionPerformed

    private void jbutton_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton_4ActionPerformed
        jtfResult.setText(jtfResult.getText() + "4");
    }//GEN-LAST:event_jbutton_4ActionPerformed

    private void jbutton_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton_5ActionPerformed
        jtfResult.setText(jtfResult.getText() + "5");
    }//GEN-LAST:event_jbutton_5ActionPerformed

    private void jbutton_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton_6ActionPerformed
        jtfResult.setText(jtfResult.getText() + "6");
    }//GEN-LAST:event_jbutton_6ActionPerformed

    private void jbutton_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton_7ActionPerformed
        jtfResult.setText(jtfResult.getText() + "7");
    }//GEN-LAST:event_jbutton_7ActionPerformed

    private void jbutton_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton_8ActionPerformed
       jtfResult.setText(jtfResult.getText() + "8");
    }//GEN-LAST:event_jbutton_8ActionPerformed

    private void jbutton_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton_9ActionPerformed
        jtfResult.setText(jtfResult.getText() + "9");
    }//GEN-LAST:event_jbutton_9ActionPerformed

    private double calc(String text) {
        double result = 0;
        ArrayList<String> number = new ArrayList();
        for (int i = 0; i < text.length(); i++) {
            if ((text.charAt(i) == '+') || (text.charAt(i) == '-')
                    || (text.charAt(i) == '*') || (text.charAt(i) == '/')) {
                number.add(text.substring(0, i));
                number.add(Character.toString(text.charAt(i)));
                text = text.substring(i + 1);
                i = 0;
            }
        }
        number.add(text);

        for (int i = 0; i < number.size(); i++) {
            if ("/".equals(number.get(i))) {
                result = Double.parseDouble(number.get(i - 1)) / Double.parseDouble(number.get(i + 1));
                number.set(i + 1, Double.toString(result));
                number.remove(i);
                number.remove(i - 1);
                i = 0;

            } else if ("*".equals(number.get(i))) {
                result = Double.parseDouble(number.get(i - 1)) * Double.parseDouble(number.get(i + 1));
                number.set(i + 1, Double.toString(result));
                number.remove(i);
                number.remove(i - 1);
                i = 0;
            }

        }

        for (int i = 0; i < number.size(); i++) {
            if ("+".equals(number.get(i))) {
                result = Double.parseDouble(number.get(i - 1)) + Double.parseDouble(number.get(i + 1));
                number.set(i + 1, Double.toString(result));
                number.remove(i);
                number.remove(i - 1);
                i = 0;

            } else if ("-".equals(number.get(i))) {
                result = Double.parseDouble(number.get(i - 1)) - Double.parseDouble(number.get(i + 1));
                number.set(i + 1, Double.toString(result));
                number.remove(i);
                number.remove(i - 1);
                i = 0;
            }

        }
        jbtEqual.setEnabled(false);
        return result;

    }

    private double fac(String number) {
        double num = 1;
        if (number.contains("+") || number.contains("-")
                || number.contains("*") || number.contains("/")) {
            for (int i = 1; i <= calc(number); i++) {
                num = num * i;
            }
            return num;
        } else {
            for (int i = 1; i <= Double.parseDouble(number); i++) {
                num = num * i;
            }
            return num;
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtAdd;
    private javax.swing.JButton jbtClear;
    private javax.swing.JButton jbtDivide;
    private javax.swing.JButton jbtEqual;
    private javax.swing.JButton jbtMultiply;
    private javax.swing.JButton jbtSubtract;
    private javax.swing.JButton jbtTan;
    private javax.swing.JButton jbtcos;
    private javax.swing.JButton jbtdecimal;
    private javax.swing.JButton jbtfac;
    private javax.swing.JButton jbtsin;
    private javax.swing.JButton jbtsqrt;
    private javax.swing.JButton jbutton_0;
    private javax.swing.JButton jbutton_1;
    private javax.swing.JButton jbutton_2;
    private javax.swing.JButton jbutton_3;
    private javax.swing.JButton jbutton_4;
    private javax.swing.JButton jbutton_5;
    private javax.swing.JButton jbutton_6;
    private javax.swing.JButton jbutton_7;
    private javax.swing.JButton jbutton_8;
    private javax.swing.JButton jbutton_9;
    private javax.swing.JTextField jtfResult;
    // End of variables declaration//GEN-END:variables
}
